nhsuk/wagtail-nhsuk-frontend

- docs/contributing.md
> Add testapp build steps to contribution docs

- docs/components/README.md
Was being nosey and noticed this broken link.
> Fix broken link to action link README

- wagtailnhsukfrontend/templates/wagtailnhsukfrontend/action_link.html
Added missing class for the action link component.
> Action link fix

- docs/components/contents_list.md
- testapp/home/templates/home/child_page.html
- testapp/home/templates/home/pagination_page.html
- tests/test_contents_list_tag.py
- wagtailnhsukfrontend/templates/wagtailnhsukfrontend/contents_list.html
- wagtailnhsukfrontend/templatetags/nhsukfrontend_tags.py
- Template tag to generate siblings list
- Template include can also be used
> Add contents list component

- CHANGELOG.md
- MANIFEST.in
- README.md
- setup.py
- Bump version number
- add a changelog
- update README
- Fix static assets bundling when releasing to pypi
> Release 0.2.0

- README.md
- docs/components/breadcrumb.md
- testapp/testapp/templates/base.html
- tests/test_breadcrumb_tag.py
- wagtailnhsukfrontend/templatetags/nhsukfrontend_tags.py
fix naming problem described in [Issue 108]
> Breadcrumb naming fix [Issue 108]

- testapp/testdata.json
- Hero image data added
- Block fixes after fieldname change. Promo, warning callout, inset text
- Upgrade to wagtail 2.4 adds a new page_ptr field
> Testdata fixture fixes after code changes

- docs/components/do.md
- docs/components/dont.md
- docs/components/image.md
- docs/components/inset_text.md
- docs/components/panel.md
Noticed a few issues when reading the docs.
Replaced all instances of `wagtailnhsstyle` with `wagtailnhsukfrontend`
Updated `InsetText` import to `InsetTextBlock`
> Fixed a few namespace issues in the documentation.

- docs/components/back_link.md
- docs/components/breadcrumb.md
- docs/components/care_card.md
- docs/components/contents_list.md
- docs/components/details.md
- docs/components/do.md
- docs/components/dont.md
- docs/components/expander.md
- docs/components/header.md
- docs/components/image.md
- docs/components/inset_text.md
- docs/components/pagination.md
- docs/components/warning_callout.md
Moved the links to one per line and added links in the reference section where missing.
> readme cleanup

- CHANGELOG.md
- setup.py
After this is merged, I'll tag a 0.3.0 release and we will see @xLasercut's azure pipeline doing it's magic 👍
> Release 0.3.0

- docs/components/header.md
- testapp/testapp/templates/base.html
- wagtailnhsukfrontend/settings/templatetags/nhsukfrontendsettings_tags.py
- wagtailnhsukfrontend/templates/wagtailnhsukfrontend/header/search.html
Add search config parameters, as have been added to the frontend-library (https://github.com/nhsuk/nhsuk-frontend/pull/461)
> Add search_action and search_field_name template parameters

- testapp/testapp/templates/404.html
- wagtailnhsukfrontend/settings/templatetags/nhsukfrontendsettings_tags.py
- wagtailnhsukfrontend/templatetags/nhsukfrontend_tags.py
Fixes https://github.com/nhsuk/wagtail-nhsuk-frontend/issues/142
@damonjagger does this look like a good solution?
> Header template without page context

- wagtailnhsukfrontend/templates/wagtailnhsukfrontend/contents_list.html
> contents-list current link should not be clickable

- CHANGELOG.md
- setup.py
Release 0.4.1 and add to changelog
> 0.4.1 release

- CHANGELOG.md
- setup.py
- Update version to 0.5.0
- More accurate changelog wording
> Bump version to 0.5.0

- wagtailnhsukfrontend/templatetags/nhsukfrontend_tags.py
It is more performant to make one query instead of lots of queries inside a loop.
Fixes #160
> Use one database query instead of a while loop

- azure-pipelines.yml
- requirements.txt
- setup.py
- testapp/requirements.txt
- testapp/testapp/settings/base.py
- testapp/testdata.json
- wagtailnhsukfrontend/templates/wagtailnhsukfrontend/favicons.html
Upgrade dependencies to latest versions and improve developer experience when installing test dependencies.
Based on https://github.com/nhsuk/wagtail-nhsuk-frontend/pull/180
> Upgrade wagtail

- tests/conftest.py
- tests/test_action_block.py
- tests/test_breadcrumb_tag.py
- tests/test_card_block.py
- tests/test_card_clickable_block.py
- tests/test_card_image_block.py
- tests/test_chunk_tag.py
- tests/test_contents_list_tag.py
- tests/test_form_tags.py
- tests/test_pagination_tag.py
- tests/test_promo_group_column_class_tag.py
- wagtailnhsukfrontend/blocks.py
I was unsure as to whether the `FlattenValueContext` mixin in `blocks.py` needed testing or not?
> Improve test coverage

- CHANGELOG.md
- README.md
- docs/components/details.md
- docs/components/expander.md
- docs/contributing.md
- setup.py
- Updated Changelog
- Updated setup.py
- Updated documentation with upgrade instructions
- Updated contributing documentation with version requirements
> prepare for v1.0.0

- README.md
- setup.py
Just correcting the readme and updating the setup file for pypi release.
> Update setup.py and correct info info in README

- testapp/forms/forms.py
- wagtailnhsukfrontend/forms/templates/forms/form_as_div.html
Add a hidden field example to the testapp
> Do not render labels or help text for hidden fields

- CHANGELOG.md
Updating the changelog for the latest fix for the callout component
> update changelog for callout component fix

- setup.py
Updating the setup to v1.5.2 and the owner of the product to Brad
> update setup.py 1.5.2
